
services:
  beq_pdfcrawler:
    container_name: beq_pdfcrawler
    image: trungthanhnguyenn/pdfcrawler:v1
    restart: always
    volumes:
      # - ./urls.txt:/app/urls.txt:ro           # Optional: URLs to crawl
      - ./output:/app/output                  # output for PDF
      - ./error.log:/app/error.log            # log file
